"""empty message

Revision ID: 13269f41a472
Revises: 0758094a0dcc
Create Date: 2020-03-02 17:58:00.386464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13269f41a472'
down_revision = '0758094a0dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=24), nullable=False),
    sa.Column('phone_number', sa.String(length=18), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('beans', sa.Float(), nullable=True),
    sa.Column('send_counter', sa.Integer(), nullable=True),
    sa.Column('receive_counter', sa.Integer(), nullable=True),
    sa.Column('wx_open_id', sa.String(length=50), nullable=True),
    sa.Column('wx_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=15), nullable=False),
    sa.Column('launched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift')
    op.drop_table('user')
    # ### end Alembic commands ###
