"""empty message

Revision ID: 3236715f1dd0
Revises: ae81b1506e9a
Create Date: 2020-03-07 14:51:14.677012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3236715f1dd0'
down_revision = 'ae81b1506e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'summary',
               existing_type=mysql.VARCHAR(length=3000),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###
