"""empty message

Revision ID: 4e491ea44715
Revises: 5427e827879c
Create Date: 2020-03-07 14:48:12.431907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e491ea44715'
down_revision = '5427e827879c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
