"""empty message

Revision ID: ecaa1a6a55e7
Revises: 3236715f1dd0
Create Date: 2020-03-07 18:46:16.631573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecaa1a6a55e7'
down_revision = '3236715f1dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('gift', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('wish', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'create_time')
    op.drop_column('user', 'create_time')
    op.drop_column('gift', 'create_time')
    op.drop_column('book', 'create_time')
    # ### end Alembic commands ###
